### ISSUE TITLE
Stuff to do

### ISSUE THREAD

**Issue by ALUKEM** [susw12/Carrom.ml#13]
- [ ] Build the game
- [ ] Create Server
- [ ] Have stats update
- [ ] Make functions to write and read database
- [ ] Create header
- [x] Create lobby
- [ ] Create chat

**Comment by susw12** [comment]
Contacts + Credits have disappeared. @ALUKEM fix that. @IlluminatiMan Finish the JS game and put it online. + make it a popup and remove the game tab. @susw12 I'll create chat.

**Comment by ALUKEM** [comment]
should we remake the credits + contacts?
